// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: artists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (name, genre, links, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, name, genre, links, notes, created_at, updated_at
`

type CreateArtistParams struct {
	Name  string      `json:"name"`
	Genre pgtype.Text `json:"genre"`
	Links pgtype.Text `json:"links"`
	Notes pgtype.Text `json:"notes"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist,
		arg.Name,
		arg.Genre,
		arg.Links,
		arg.Notes,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genre,
		&i.Links,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtist = `-- name: GetArtist :one
SELECT id, name, genre, links, notes, created_at, updated_at FROM artists WHERE id = $1
`

func (q *Queries) GetArtist(ctx context.Context, id int32) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genre,
		&i.Links,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, genre, links, notes, created_at, updated_at FROM artists WHERE name = $1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genre,
		&i.Links,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtists = `-- name: ListArtists :many
SELECT id, name, genre, links, notes, created_at, updated_at FROM artists ORDER BY name ASC
`

func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artist{}
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Genre,
			&i.Links,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE artists
SET name = $2, genre = $3, links = $4, notes = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, genre, links, notes, created_at, updated_at
`

type UpdateArtistParams struct {
	ID    int32       `json:"id"`
	Name  string      `json:"name"`
	Genre pgtype.Text `json:"genre"`
	Links pgtype.Text `json:"links"`
	Notes pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist,
		arg.ID,
		arg.Name,
		arg.Genre,
		arg.Links,
		arg.Notes,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Genre,
		&i.Links,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
