// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: attendance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttendanceLog = `-- name: GetAttendanceLog :one
SELECT id, show_id, draw, notes, incident, incident_notes, logged_by, created_at, updated_at FROM attendance_logs WHERE show_id = $1
`

func (q *Queries) GetAttendanceLog(ctx context.Context, showID int32) (AttendanceLog, error) {
	row := q.db.QueryRow(ctx, getAttendanceLog, showID)
	var i AttendanceLog
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.Draw,
		&i.Notes,
		&i.Incident,
		&i.IncidentNotes,
		&i.LoggedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttendanceLogs = `-- name: ListAttendanceLogs :many
SELECT al.id, al.show_id, al.draw, al.notes, al.incident, al.incident_notes, al.logged_by, al.created_at, al.updated_at, s.artist, s.date
FROM attendance_logs al
JOIN shows s ON s.id = al.show_id
ORDER BY s.date DESC
LIMIT $1 OFFSET $2
`

type ListAttendanceLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAttendanceLogsRow struct {
	ID            int32              `json:"id"`
	ShowID        int32              `json:"showId"`
	Draw          pgtype.Int4        `json:"draw"`
	Notes         pgtype.Text        `json:"notes"`
	Incident      pgtype.Bool        `json:"incident"`
	IncidentNotes pgtype.Text        `json:"incidentNotes"`
	LoggedBy      pgtype.Int4        `json:"loggedBy"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	Artist        string             `json:"artist"`
	Date          pgtype.Date        `json:"date"`
}

func (q *Queries) ListAttendanceLogs(ctx context.Context, arg ListAttendanceLogsParams) ([]ListAttendanceLogsRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceLogsRow{}
	for rows.Next() {
		var i ListAttendanceLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShowID,
			&i.Draw,
			&i.Notes,
			&i.Incident,
			&i.IncidentNotes,
			&i.LoggedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Artist,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttendanceLog = `-- name: UpsertAttendanceLog :one
INSERT INTO attendance_logs (show_id, draw, notes, incident, incident_notes, logged_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (show_id) DO UPDATE SET
    draw = EXCLUDED.draw,
    notes = EXCLUDED.notes,
    incident = EXCLUDED.incident,
    incident_notes = EXCLUDED.incident_notes,
    logged_by = EXCLUDED.logged_by,
    updated_at = NOW()
RETURNING id, show_id, draw, notes, incident, incident_notes, logged_by, created_at, updated_at
`

type UpsertAttendanceLogParams struct {
	ShowID        int32       `json:"showId"`
	Draw          pgtype.Int4 `json:"draw"`
	Notes         pgtype.Text `json:"notes"`
	Incident      pgtype.Bool `json:"incident"`
	IncidentNotes pgtype.Text `json:"incidentNotes"`
	LoggedBy      pgtype.Int4 `json:"loggedBy"`
}

func (q *Queries) UpsertAttendanceLog(ctx context.Context, arg UpsertAttendanceLogParams) (AttendanceLog, error) {
	row := q.db.QueryRow(ctx, upsertAttendanceLog,
		arg.ShowID,
		arg.Draw,
		arg.Notes,
		arg.Incident,
		arg.IncidentNotes,
		arg.LoggedBy,
	)
	var i AttendanceLog
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.Draw,
		&i.Notes,
		&i.Incident,
		&i.IncidentNotes,
		&i.LoggedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
