// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string             `json:"id"`
	UserID    int32              `json:"userId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, expires_at, created_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, discord_id, discord_username, avatar_url, role, created_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertDevUser = `-- name: UpsertDevUser :one
INSERT INTO users (discord_id, discord_username, avatar_url, role, last_login_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (discord_id) DO UPDATE SET
    discord_username = EXCLUDED.discord_username,
    avatar_url = EXCLUDED.avatar_url,
    role = EXCLUDED.role,
    last_login_at = NOW()
RETURNING id, discord_id, discord_username, avatar_url, role, created_at, last_login_at
`

type UpsertDevUserParams struct {
	DiscordID       string      `json:"discordId"`
	DiscordUsername string      `json:"discordUsername"`
	AvatarUrl       pgtype.Text `json:"avatarUrl"`
	Role            string      `json:"role"`
}

func (q *Queries) UpsertDevUser(ctx context.Context, arg UpsertDevUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertDevUser,
		arg.DiscordID,
		arg.DiscordUsername,
		arg.AvatarUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (discord_id, discord_username, avatar_url, role, last_login_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (discord_id) DO UPDATE SET
    discord_username = EXCLUDED.discord_username,
    avatar_url = EXCLUDED.avatar_url,
    role = EXCLUDED.role,
    last_login_at = NOW()
RETURNING id, discord_id, discord_username, avatar_url, role, created_at, last_login_at
`

type UpsertUserParams struct {
	DiscordID       string      `json:"discordId"`
	DiscordUsername string      `json:"discordUsername"`
	AvatarUrl       pgtype.Text `json:"avatarUrl"`
	Role            string      `json:"role"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.DiscordID,
		arg.DiscordUsername,
		arg.AvatarUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
