// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: booking_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBookingReview = `-- name: GetBookingReview :one
SELECT submission_id, note, decision, updated_by, updated_at FROM booking_reviews WHERE submission_id = $1
`

func (q *Queries) GetBookingReview(ctx context.Context, submissionID int32) (BookingReview, error) {
	row := q.db.QueryRow(ctx, getBookingReview, submissionID)
	var i BookingReview
	err := row.Scan(
		&i.SubmissionID,
		&i.Note,
		&i.Decision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBookingReview = `-- name: UpsertBookingReview :one
INSERT INTO booking_reviews (submission_id, note, decision, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (submission_id) DO UPDATE
SET note = EXCLUDED.note,
    decision = EXCLUDED.decision,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING submission_id, note, decision, updated_by, updated_at
`

type UpsertBookingReviewParams struct {
	SubmissionID int32       `json:"submissionId"`
	Note         string      `json:"note"`
	Decision     string      `json:"decision"`
	UpdatedBy    pgtype.Int4 `json:"updatedBy"`
}

func (q *Queries) UpsertBookingReview(ctx context.Context, arg UpsertBookingReviewParams) (BookingReview, error) {
	row := q.db.QueryRow(ctx, upsertBookingReview,
		arg.SubmissionID,
		arg.Note,
		arg.Decision,
		arg.UpdatedBy,
	)
	var i BookingReview
	err := row.Scan(
		&i.SubmissionID,
		&i.Note,
		&i.Decision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
