// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: calendar.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendarBlocked = `-- name: CreateCalendarBlocked :one
INSERT INTO calendar_blocked (date, reason, created_by)
VALUES ($1, $2, $3)
RETURNING id, date, reason, created_by, created_at
`

type CreateCalendarBlockedParams struct {
	Date      pgtype.Date `json:"date"`
	Reason    pgtype.Text `json:"reason"`
	CreatedBy pgtype.Int4 `json:"createdBy"`
}

func (q *Queries) CreateCalendarBlocked(ctx context.Context, arg CreateCalendarBlockedParams) (CalendarBlocked, error) {
	row := q.db.QueryRow(ctx, createCalendarBlocked, arg.Date, arg.Reason, arg.CreatedBy)
	var i CalendarBlocked
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createCalendarHold = `-- name: CreateCalendarHold :one
INSERT INTO calendar_holds (date, label, created_by)
VALUES ($1, $2, $3)
RETURNING id, date, label, created_by, created_at
`

type CreateCalendarHoldParams struct {
	Date      pgtype.Date `json:"date"`
	Label     pgtype.Text `json:"label"`
	CreatedBy pgtype.Int4 `json:"createdBy"`
}

func (q *Queries) CreateCalendarHold(ctx context.Context, arg CreateCalendarHoldParams) (CalendarHold, error) {
	row := q.db.QueryRow(ctx, createCalendarHold, arg.Date, arg.Label, arg.CreatedBy)
	var i CalendarHold
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Label,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCalendarBlocked = `-- name: DeleteCalendarBlocked :exec
DELETE FROM calendar_blocked WHERE id = $1
`

func (q *Queries) DeleteCalendarBlocked(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCalendarBlocked, id)
	return err
}

const deleteCalendarHold = `-- name: DeleteCalendarHold :exec
DELETE FROM calendar_holds WHERE id = $1
`

func (q *Queries) DeleteCalendarHold(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCalendarHold, id)
	return err
}

const listCalendarBlocked = `-- name: ListCalendarBlocked :many
SELECT id, date, reason, created_by, created_at FROM calendar_blocked ORDER BY date ASC
`

func (q *Queries) ListCalendarBlocked(ctx context.Context) ([]CalendarBlocked, error) {
	rows, err := q.db.Query(ctx, listCalendarBlocked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarBlocked{}
	for rows.Next() {
		var i CalendarBlocked
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarHolds = `-- name: ListCalendarHolds :many
SELECT id, date, label, created_by, created_at FROM calendar_holds ORDER BY date ASC
`

func (q *Queries) ListCalendarHolds(ctx context.Context) ([]CalendarHold, error) {
	rows, err := q.db.Query(ctx, listCalendarHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarHold{}
	for rows.Next() {
		var i CalendarHold
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Label,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
