// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Genre     pgtype.Text        `json:"genre"`
	Links     pgtype.Text        `json:"links"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type AuditLog struct {
	ID         int32              `json:"id"`
	Actor      string             `json:"actor"`
	ActorID    pgtype.Int4        `json:"actorId"`
	Action     string             `json:"action"`
	EntityType pgtype.Text        `json:"entityType"`
	EntityID   pgtype.Int4        `json:"entityId"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type BookingReview struct {
	SubmissionID int32              `json:"submissionId"`
	Note         string             `json:"note"`
	Decision     string             `json:"decision"`
	UpdatedBy    pgtype.Int4        `json:"updatedBy"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type CalendarBlocked struct {
	ID        int32              `json:"id"`
	Date      pgtype.Date        `json:"date"`
	Reason    pgtype.Text        `json:"reason"`
	CreatedBy pgtype.Int4        `json:"createdBy"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type CalendarHold struct {
	ID        int32              `json:"id"`
	Date      pgtype.Date        `json:"date"`
	Label     pgtype.Text        `json:"label"`
	CreatedBy pgtype.Int4        `json:"createdBy"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    int32              `json:"userId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type Setting struct {
	ID                     int32              `json:"id"`
	SpaceName              string             `json:"spaceName"`
	Tagline                pgtype.Text        `json:"tagline"`
	Address                pgtype.Text        `json:"address"`
	Capacity               pgtype.Int4        `json:"capacity"`
	ContactEmail           pgtype.Text        `json:"contactEmail"`
	Website                pgtype.Text        `json:"website"`
	DiscordGuildID         pgtype.Text        `json:"discordGuildId"`
	DiscordChUpcoming      pgtype.Text        `json:"discordChUpcoming"`
	DiscordChAnnouncements pgtype.Text        `json:"discordChAnnouncements"`
	DiscordChStaff         pgtype.Text        `json:"discordChStaff"`
	DiscordChBookings      pgtype.Text        `json:"discordChBookings"`
	SetupComplete          pgtype.Bool        `json:"setupComplete"`
	UpdatedAt              pgtype.Timestamptz `json:"updatedAt"`
	Timezone               pgtype.Text        `json:"timezone"`
	BookingEmail           pgtype.Text        `json:"bookingEmail"`
	AutoArchive            pgtype.Bool        `json:"autoArchive"`
	DiscordPosting         pgtype.Bool        `json:"discordPosting"`
	SafeSpaceRequired      pgtype.Bool        `json:"safeSpaceRequired"`
}

type Show struct {
	ID               int32              `json:"id"`
	Artist           string             `json:"artist"`
	Date             pgtype.Date        `json:"date"`
	DoorsTime        pgtype.Text        `json:"doorsTime"`
	StartTime        pgtype.Text        `json:"startTime"`
	Age              pgtype.Text        `json:"age"`
	Price            pgtype.Text        `json:"price"`
	Genre            pgtype.Text        `json:"genre"`
	Description      pgtype.Text        `json:"description"`
	Notes            pgtype.Text        `json:"notes"`
	Status           string             `json:"status"`
	FlyerUrl         pgtype.Text        `json:"flyerUrl"`
	DiscordMessageID pgtype.Text        `json:"discordMessageId"`
	DiscordChannelID pgtype.Text        `json:"discordChannelId"`
	SubmissionID     pgtype.Int4        `json:"submissionId"`
	ArtistID         pgtype.Int4        `json:"artistId"`
	CreatedBy        pgtype.Int4        `json:"createdBy"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
	Draw             pgtype.Int4        `json:"draw"`
	Capacity         pgtype.Int4        `json:"capacity"`
}

type ShowLineup struct {
	ID        int32       `json:"id"`
	ShowID    int32       `json:"showId"`
	Artist    string      `json:"artist"`
	Role      string      `json:"role"`
	StartTime pgtype.Text `json:"startTime"`
	EndTime   pgtype.Text `json:"endTime"`
	SortOrder int32       `json:"sortOrder"`
}

type ShowLog struct {
	ID             int32              `json:"id"`
	ShowID         int32              `json:"showId"`
	Draw           pgtype.Int4        `json:"draw"`
	Notes          pgtype.Text        `json:"notes"`
	Incident       pgtype.Bool        `json:"incident"`
	IncidentNotes  pgtype.Text        `json:"incidentNotes"`
	LoggedBy       pgtype.Int4        `json:"loggedBy"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	QuickHighlight pgtype.Text        `json:"quickHighlight"`
	TotalDoorCents pgtype.Int4        `json:"totalDoorCents"`
}

type Submission struct {
	ID             int32              `json:"id"`
	ArtistID       pgtype.Int4        `json:"artistId"`
	ArtistName     string             `json:"artistName"`
	PreferredDate  pgtype.Date        `json:"preferredDate"`
	Genre          pgtype.Text        `json:"genre"`
	ExpectedDraw   pgtype.Int4        `json:"expectedDraw"`
	Links          pgtype.Text        `json:"links"`
	TechRider      pgtype.Text        `json:"techRider"`
	Message        pgtype.Text        `json:"message"`
	ContactDiscord pgtype.Text        `json:"contactDiscord"`
	Status         string             `json:"status"`
	ReviewedBy     pgtype.Int4        `json:"reviewedBy"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewedAt"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID              int32              `json:"id"`
	DiscordID       string             `json:"discordId"`
	DiscordUsername string             `json:"discordUsername"`
	AvatarUrl       pgtype.Text        `json:"avatarUrl"`
	Role            string             `json:"role"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	LastLoginAt     pgtype.Timestamptz `json:"lastLoginAt"`
}
