// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	ArchiveShow(ctx context.Context, id int32) (Show, error)
	CreateShow(ctx context.Context, arg CreateShowParams) (Show, error)
	GetArchiveStats(ctx context.Context) (GetArchiveStatsRow, error)
	GetShow(ctx context.Context, id int32) (Show, error)
	GetShowWithLineup(ctx context.Context, id int32) (GetShowWithLineupRow, error)
	ListUpcomingShows(ctx context.Context) ([]ListUpcomingShowsRow, error)
	SearchArchive(ctx context.Context, dollar_1 string) ([]SearchArchiveRow, error)
	UpdateShow(ctx context.Context, arg UpdateShowParams) (Show, error)
}

var _ Querier = (*Queries)(nil)
