// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	ApproveSubmission(ctx context.Context, arg ApproveSubmissionParams) (Submission, error)
	ArchiveShow(ctx context.Context, id int32) (Show, error)
	CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShow(ctx context.Context, arg CreateShowParams) (Show, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	DeclineSubmission(ctx context.Context, arg DeclineSubmissionParams) (Submission, error)
	DeleteSession(ctx context.Context, id string) error
	GetArchiveStats(ctx context.Context) (GetArchiveStatsRow, error)
	GetArtist(ctx context.Context, id int32) (Artist, error)
	GetArtistByName(ctx context.Context, name string) (Artist, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetShow(ctx context.Context, id int32) (Show, error)
	GetShowWithLineup(ctx context.Context, id int32) (GetShowWithLineupRow, error)
	GetSubmission(ctx context.Context, id int32) (Submission, error)
	GetUser(ctx context.Context, id int32) (User, error)
	ListAllShows(ctx context.Context) ([]Show, error)
	ListArtists(ctx context.Context) ([]Artist, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	ListSubmissions(ctx context.Context, dollar_1 interface{}) ([]Submission, error)
	ListUpcomingShows(ctx context.Context) ([]ListUpcomingShowsRow, error)
	SearchArchive(ctx context.Context, dollar_1 string) ([]SearchArchiveRow, error)
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error)
	UpdateShow(ctx context.Context, arg UpdateShowParams) (Show, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
