// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSettings = `-- name: GetSettings :one
SELECT id, space_name, tagline, address, capacity, contact_email, website, discord_guild_id, discord_ch_upcoming, discord_ch_announcements, discord_ch_staff, discord_ch_bookings, setup_complete, updated_at, timezone, booking_email, auto_archive, discord_posting, safe_space_required FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SpaceName,
		&i.Tagline,
		&i.Address,
		&i.Capacity,
		&i.ContactEmail,
		&i.Website,
		&i.DiscordGuildID,
		&i.DiscordChUpcoming,
		&i.DiscordChAnnouncements,
		&i.DiscordChStaff,
		&i.DiscordChBookings,
		&i.SetupComplete,
		&i.UpdatedAt,
		&i.Timezone,
		&i.BookingEmail,
		&i.AutoArchive,
		&i.DiscordPosting,
		&i.SafeSpaceRequired,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET space_name = COALESCE($1, space_name),
    tagline = COALESCE($2, tagline),
    address = COALESCE($3, address),
    capacity = COALESCE($4, capacity),
    contact_email = COALESCE($5, contact_email),
    website = COALESCE($6, website),
    discord_guild_id = COALESCE($7, discord_guild_id),
    discord_ch_upcoming = COALESCE($8, discord_ch_upcoming),
    discord_ch_announcements = COALESCE($9, discord_ch_announcements),
    discord_ch_staff = COALESCE($10, discord_ch_staff),
    discord_ch_bookings = COALESCE($11, discord_ch_bookings),
    setup_complete = COALESCE($12, setup_complete),
    timezone = COALESCE($13, timezone),
    booking_email = COALESCE($14, booking_email),
    auto_archive = COALESCE($15, auto_archive),
    discord_posting = COALESCE($16, discord_posting),
    safe_space_required = COALESCE($17, safe_space_required),
    updated_at = NOW()
WHERE id = 1
RETURNING id, space_name, tagline, address, capacity, contact_email, website, discord_guild_id, discord_ch_upcoming, discord_ch_announcements, discord_ch_staff, discord_ch_bookings, setup_complete, updated_at, timezone, booking_email, auto_archive, discord_posting, safe_space_required
`

type UpdateSettingsParams struct {
	SpaceName              string      `json:"spaceName"`
	Tagline                pgtype.Text `json:"tagline"`
	Address                pgtype.Text `json:"address"`
	Capacity               pgtype.Int4 `json:"capacity"`
	ContactEmail           pgtype.Text `json:"contactEmail"`
	Website                pgtype.Text `json:"website"`
	DiscordGuildID         pgtype.Text `json:"discordGuildId"`
	DiscordChUpcoming      pgtype.Text `json:"discordChUpcoming"`
	DiscordChAnnouncements pgtype.Text `json:"discordChAnnouncements"`
	DiscordChStaff         pgtype.Text `json:"discordChStaff"`
	DiscordChBookings      pgtype.Text `json:"discordChBookings"`
	SetupComplete          pgtype.Bool `json:"setupComplete"`
	Timezone               pgtype.Text `json:"timezone"`
	BookingEmail           pgtype.Text `json:"bookingEmail"`
	AutoArchive            pgtype.Bool `json:"autoArchive"`
	DiscordPosting         pgtype.Bool `json:"discordPosting"`
	SafeSpaceRequired      pgtype.Bool `json:"safeSpaceRequired"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings,
		arg.SpaceName,
		arg.Tagline,
		arg.Address,
		arg.Capacity,
		arg.ContactEmail,
		arg.Website,
		arg.DiscordGuildID,
		arg.DiscordChUpcoming,
		arg.DiscordChAnnouncements,
		arg.DiscordChStaff,
		arg.DiscordChBookings,
		arg.SetupComplete,
		arg.Timezone,
		arg.BookingEmail,
		arg.AutoArchive,
		arg.DiscordPosting,
		arg.SafeSpaceRequired,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SpaceName,
		&i.Tagline,
		&i.Address,
		&i.Capacity,
		&i.ContactEmail,
		&i.Website,
		&i.DiscordGuildID,
		&i.DiscordChUpcoming,
		&i.DiscordChAnnouncements,
		&i.DiscordChStaff,
		&i.DiscordChBookings,
		&i.SetupComplete,
		&i.UpdatedAt,
		&i.Timezone,
		&i.BookingEmail,
		&i.AutoArchive,
		&i.DiscordPosting,
		&i.SafeSpaceRequired,
	)
	return i, err
}
