// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: shows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveShow = `-- name: ArchiveShow :one
UPDATE shows AS s SET status = 'archived', updated_at = NOW() WHERE s.id = $1 RETURNING s.id, s.artist, s.date, s.doors_time, s.start_time, s.age, s.price, s.genre, s.description, s.notes, s.status, s.flyer_url, s.discord_message_id, s.discord_channel_id, s.submission_id, s.artist_id, s.created_by, s.created_at, s.updated_at
`

func (q *Queries) ArchiveShow(ctx context.Context, id int32) (Show, error) {
	row := q.db.QueryRow(ctx, archiveShow, id)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Date,
		&i.DoorsTime,
		&i.StartTime,
		&i.Age,
		&i.Price,
		&i.Genre,
		&i.Description,
		&i.Notes,
		&i.Status,
		&i.FlyerUrl,
		&i.DiscordMessageID,
		&i.DiscordChannelID,
		&i.SubmissionID,
		&i.ArtistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShow = `-- name: CreateShow :one
INSERT INTO shows (artist, date, doors_time, start_time, age, price,
                   genre, description, status, submission_id, artist_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, artist, date, doors_time, start_time, age, price, genre, description, notes, status, flyer_url, discord_message_id, discord_channel_id, submission_id, artist_id, created_by, created_at, updated_at
`

type CreateShowParams struct {
	Artist       string      `json:"artist"`
	Date         pgtype.Date `json:"date"`
	DoorsTime    pgtype.Text `json:"doorsTime"`
	StartTime    pgtype.Text `json:"startTime"`
	Age          pgtype.Text `json:"age"`
	Price        pgtype.Text `json:"price"`
	Genre        pgtype.Text `json:"genre"`
	Description  pgtype.Text `json:"description"`
	Status       string      `json:"status"`
	SubmissionID pgtype.Int4 `json:"submissionId"`
	ArtistID     pgtype.Int4 `json:"artistId"`
	CreatedBy    pgtype.Int4 `json:"createdBy"`
}

func (q *Queries) CreateShow(ctx context.Context, arg CreateShowParams) (Show, error) {
	row := q.db.QueryRow(ctx, createShow,
		arg.Artist,
		arg.Date,
		arg.DoorsTime,
		arg.StartTime,
		arg.Age,
		arg.Price,
		arg.Genre,
		arg.Description,
		arg.Status,
		arg.SubmissionID,
		arg.ArtistID,
		arg.CreatedBy,
	)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Date,
		&i.DoorsTime,
		&i.StartTime,
		&i.Age,
		&i.Price,
		&i.Genre,
		&i.Description,
		&i.Notes,
		&i.Status,
		&i.FlyerUrl,
		&i.DiscordMessageID,
		&i.DiscordChannelID,
		&i.SubmissionID,
		&i.ArtistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArchiveStats = `-- name: GetArchiveStats :one
SELECT
    COUNT(*) as total_shows,
    COALESCE(SUM(al.draw), 0) as total_attendance,
    COUNT(DISTINCT date_part('year', date)) as years_running,
    COUNT(DISTINCT artist_id) as unique_artists
FROM shows s
LEFT JOIN attendance_logs al ON al.show_id = s.id
WHERE s.status = 'archived'
`

type GetArchiveStatsRow struct {
	TotalShows      int64       `json:"totalShows"`
	TotalAttendance interface{} `json:"totalAttendance"`
	YearsRunning    int64       `json:"yearsRunning"`
	UniqueArtists   int64       `json:"uniqueArtists"`
}

func (q *Queries) GetArchiveStats(ctx context.Context) (GetArchiveStatsRow, error) {
	row := q.db.QueryRow(ctx, getArchiveStats)
	var i GetArchiveStatsRow
	err := row.Scan(
		&i.TotalShows,
		&i.TotalAttendance,
		&i.YearsRunning,
		&i.UniqueArtists,
	)
	return i, err
}

const getShow = `-- name: GetShow :one
SELECT id, artist, date, doors_time, start_time, age, price, genre, description, notes, status, flyer_url, discord_message_id, discord_channel_id, submission_id, artist_id, created_by, created_at, updated_at FROM shows WHERE id = $1
`

func (q *Queries) GetShow(ctx context.Context, id int32) (Show, error) {
	row := q.db.QueryRow(ctx, getShow, id)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Date,
		&i.DoorsTime,
		&i.StartTime,
		&i.Age,
		&i.Price,
		&i.Genre,
		&i.Description,
		&i.Notes,
		&i.Status,
		&i.FlyerUrl,
		&i.DiscordMessageID,
		&i.DiscordChannelID,
		&i.SubmissionID,
		&i.ArtistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShowWithLineup = `-- name: GetShowWithLineup :one
SELECT
    s.id, s.artist, s.date, s.doors_time, s.start_time, s.age, s.price, s.genre, s.description, s.notes, s.status, s.flyer_url, s.discord_message_id, s.discord_channel_id, s.submission_id, s.artist_id, s.created_by, s.created_at, s.updated_at,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'artist', sl.artist,
                'role', sl.role,
                'startTime', sl.start_time,
                'endTime', sl.end_time
            ) ORDER BY sl.sort_order
        ) FILTER (WHERE sl.id IS NOT NULL),
        '[]'::jsonb
    ) as lineup
FROM shows s
LEFT JOIN show_lineup sl ON sl.show_id = s.id
WHERE s.id = $1
GROUP BY s.id
`

type GetShowWithLineupRow struct {
	ID               int32              `json:"id"`
	Artist           string             `json:"artist"`
	Date             pgtype.Date        `json:"date"`
	DoorsTime        pgtype.Text        `json:"doorsTime"`
	StartTime        pgtype.Text        `json:"startTime"`
	Age              pgtype.Text        `json:"age"`
	Price            pgtype.Text        `json:"price"`
	Genre            pgtype.Text        `json:"genre"`
	Description      pgtype.Text        `json:"description"`
	Notes            pgtype.Text        `json:"notes"`
	Status           string             `json:"status"`
	FlyerUrl         pgtype.Text        `json:"flyerUrl"`
	DiscordMessageID pgtype.Text        `json:"discordMessageId"`
	DiscordChannelID pgtype.Text        `json:"discordChannelId"`
	SubmissionID     pgtype.Int4        `json:"submissionId"`
	ArtistID         pgtype.Int4        `json:"artistId"`
	CreatedBy        pgtype.Int4        `json:"createdBy"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
	Lineup           interface{}        `json:"lineup"`
}

func (q *Queries) GetShowWithLineup(ctx context.Context, id int32) (GetShowWithLineupRow, error) {
	row := q.db.QueryRow(ctx, getShowWithLineup, id)
	var i GetShowWithLineupRow
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Date,
		&i.DoorsTime,
		&i.StartTime,
		&i.Age,
		&i.Price,
		&i.Genre,
		&i.Description,
		&i.Notes,
		&i.Status,
		&i.FlyerUrl,
		&i.DiscordMessageID,
		&i.DiscordChannelID,
		&i.SubmissionID,
		&i.ArtistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lineup,
	)
	return i, err
}

const listAllShows = `-- name: ListAllShows :many
SELECT id, artist, date, doors_time, start_time, age, price, genre, description, notes, status, flyer_url, discord_message_id, discord_channel_id, submission_id, artist_id, created_by, created_at, updated_at FROM shows ORDER BY date DESC
`

func (q *Queries) ListAllShows(ctx context.Context) ([]Show, error) {
	rows, err := q.db.Query(ctx, listAllShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Show{}
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Date,
			&i.DoorsTime,
			&i.StartTime,
			&i.Age,
			&i.Price,
			&i.Genre,
			&i.Description,
			&i.Notes,
			&i.Status,
			&i.FlyerUrl,
			&i.DiscordMessageID,
			&i.DiscordChannelID,
			&i.SubmissionID,
			&i.ArtistID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingShows = `-- name: ListUpcomingShows :many
SELECT id, artist, date, doors_time, start_time, age, price, genre,
       description, status, flyer_url, submission_id, artist_id,
       created_at, updated_at
FROM shows
WHERE status = 'confirmed' AND date >= CURRENT_DATE
ORDER BY date ASC
`

type ListUpcomingShowsRow struct {
	ID           int32              `json:"id"`
	Artist       string             `json:"artist"`
	Date         pgtype.Date        `json:"date"`
	DoorsTime    pgtype.Text        `json:"doorsTime"`
	StartTime    pgtype.Text        `json:"startTime"`
	Age          pgtype.Text        `json:"age"`
	Price        pgtype.Text        `json:"price"`
	Genre        pgtype.Text        `json:"genre"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	FlyerUrl     pgtype.Text        `json:"flyerUrl"`
	SubmissionID pgtype.Int4        `json:"submissionId"`
	ArtistID     pgtype.Int4        `json:"artistId"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListUpcomingShows(ctx context.Context) ([]ListUpcomingShowsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingShowsRow{}
	for rows.Next() {
		var i ListUpcomingShowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Date,
			&i.DoorsTime,
			&i.StartTime,
			&i.Age,
			&i.Price,
			&i.Genre,
			&i.Description,
			&i.Status,
			&i.FlyerUrl,
			&i.SubmissionID,
			&i.ArtistID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArchive = `-- name: SearchArchive :many
SELECT s.id, s.artist, s.date, s.genre, COALESCE(al.draw, 0) as draw
FROM shows s
LEFT JOIN attendance_logs al ON al.show_id = s.id
WHERE s.status = 'archived'
  AND ($1::text = '' OR s.artist ILIKE '%' || $1 || '%' OR s.genre ILIKE '%' || $1 || '%')
ORDER BY s.date DESC
`

type SearchArchiveRow struct {
	ID     int32       `json:"id"`
	Artist string      `json:"artist"`
	Date   pgtype.Date `json:"date"`
	Genre  pgtype.Text `json:"genre"`
	Draw   int32       `json:"draw"`
}

func (q *Queries) SearchArchive(ctx context.Context, dollar_1 string) ([]SearchArchiveRow, error) {
	rows, err := q.db.Query(ctx, searchArchive, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArchiveRow{}
	for rows.Next() {
		var i SearchArchiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Date,
			&i.Genre,
			&i.Draw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShow = `-- name: UpdateShow :one
UPDATE shows
SET artist = $2, date = $3, doors_time = $4, start_time = $5,
    age = $6, price = $7, genre = $8, description = $9, status = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, artist, date, doors_time, start_time, age, price, genre, description, notes, status, flyer_url, discord_message_id, discord_channel_id, submission_id, artist_id, created_by, created_at, updated_at
`

type UpdateShowParams struct {
	ID          int32       `json:"id"`
	Artist      string      `json:"artist"`
	Date        pgtype.Date `json:"date"`
	DoorsTime   pgtype.Text `json:"doorsTime"`
	StartTime   pgtype.Text `json:"startTime"`
	Age         pgtype.Text `json:"age"`
	Price       pgtype.Text `json:"price"`
	Genre       pgtype.Text `json:"genre"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateShow(ctx context.Context, arg UpdateShowParams) (Show, error) {
	row := q.db.QueryRow(ctx, updateShow,
		arg.ID,
		arg.Artist,
		arg.Date,
		arg.DoorsTime,
		arg.StartTime,
		arg.Age,
		arg.Price,
		arg.Genre,
		arg.Description,
		arg.Status,
	)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Date,
		&i.DoorsTime,
		&i.StartTime,
		&i.Age,
		&i.Price,
		&i.Genre,
		&i.Description,
		&i.Notes,
		&i.Status,
		&i.FlyerUrl,
		&i.DiscordMessageID,
		&i.DiscordChannelID,
		&i.SubmissionID,
		&i.ArtistID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
