// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: submissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveSubmission = `-- name: ApproveSubmission :one
UPDATE submissions
SET status = 'approved', reviewed_by = $2, reviewed_at = NOW()
WHERE id = $1
RETURNING id, artist_id, artist_name, preferred_date, genre, expected_draw, links, tech_rider, message, contact_discord, status, reviewed_by, reviewed_at, created_at
`

type ApproveSubmissionParams struct {
	ID         int32       `json:"id"`
	ReviewedBy pgtype.Int4 `json:"reviewedBy"`
}

func (q *Queries) ApproveSubmission(ctx context.Context, arg ApproveSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, approveSubmission, arg.ID, arg.ReviewedBy)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ArtistName,
		&i.PreferredDate,
		&i.Genre,
		&i.ExpectedDraw,
		&i.Links,
		&i.TechRider,
		&i.Message,
		&i.ContactDiscord,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (artist_name, preferred_date, genre, expected_draw, links, tech_rider, message, contact_discord, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending')
RETURNING id, artist_id, artist_name, preferred_date, genre, expected_draw, links, tech_rider, message, contact_discord, status, reviewed_by, reviewed_at, created_at
`

type CreateSubmissionParams struct {
	ArtistName     string      `json:"artistName"`
	PreferredDate  pgtype.Date `json:"preferredDate"`
	Genre          pgtype.Text `json:"genre"`
	ExpectedDraw   pgtype.Int4 `json:"expectedDraw"`
	Links          pgtype.Text `json:"links"`
	TechRider      pgtype.Text `json:"techRider"`
	Message        pgtype.Text `json:"message"`
	ContactDiscord pgtype.Text `json:"contactDiscord"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ArtistName,
		arg.PreferredDate,
		arg.Genre,
		arg.ExpectedDraw,
		arg.Links,
		arg.TechRider,
		arg.Message,
		arg.ContactDiscord,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ArtistName,
		&i.PreferredDate,
		&i.Genre,
		&i.ExpectedDraw,
		&i.Links,
		&i.TechRider,
		&i.Message,
		&i.ContactDiscord,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const declineSubmission = `-- name: DeclineSubmission :one
UPDATE submissions
SET status = 'declined', reviewed_by = $2, reviewed_at = NOW()
WHERE id = $1
RETURNING id, artist_id, artist_name, preferred_date, genre, expected_draw, links, tech_rider, message, contact_discord, status, reviewed_by, reviewed_at, created_at
`

type DeclineSubmissionParams struct {
	ID         int32       `json:"id"`
	ReviewedBy pgtype.Int4 `json:"reviewedBy"`
}

func (q *Queries) DeclineSubmission(ctx context.Context, arg DeclineSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, declineSubmission, arg.ID, arg.ReviewedBy)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ArtistName,
		&i.PreferredDate,
		&i.Genre,
		&i.ExpectedDraw,
		&i.Links,
		&i.TechRider,
		&i.Message,
		&i.ContactDiscord,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, artist_id, artist_name, preferred_date, genre, expected_draw, links, tech_rider, message, contact_discord, status, reviewed_by, reviewed_at, created_at FROM submissions WHERE id = $1
`

func (q *Queries) GetSubmission(ctx context.Context, id int32) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ArtistName,
		&i.PreferredDate,
		&i.Genre,
		&i.ExpectedDraw,
		&i.Links,
		&i.TechRider,
		&i.Message,
		&i.ContactDiscord,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, artist_id, artist_name, preferred_date, genre, expected_draw, links, tech_rider, message, contact_discord, status, reviewed_by, reviewed_at, created_at FROM submissions WHERE ($1 = '' OR status = $1) ORDER BY created_at DESC
`

func (q *Queries) ListSubmissions(ctx context.Context, dollar_1 interface{}) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.ArtistName,
			&i.PreferredDate,
			&i.Genre,
			&i.ExpectedDraw,
			&i.Links,
			&i.TechRider,
			&i.Message,
			&i.ContactDiscord,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmissionDetails = `-- name: UpdateSubmissionDetails :one
UPDATE submissions
SET artist_name = $2,
    preferred_date = $3,
    genre = $4,
    expected_draw = $5,
    links = $6,
    tech_rider = $7,
    message = $8,
    contact_discord = $9,
    status = COALESCE($10, status)
WHERE id = $1
RETURNING id, artist_id, artist_name, preferred_date, genre, expected_draw, links, tech_rider, message, contact_discord, status, reviewed_by, reviewed_at, created_at
`

type UpdateSubmissionDetailsParams struct {
	ID             int32       `json:"id"`
	ArtistName     string      `json:"artistName"`
	PreferredDate  pgtype.Date `json:"preferredDate"`
	Genre          pgtype.Text `json:"genre"`
	ExpectedDraw   pgtype.Int4 `json:"expectedDraw"`
	Links          pgtype.Text `json:"links"`
	TechRider      pgtype.Text `json:"techRider"`
	Message        pgtype.Text `json:"message"`
	ContactDiscord pgtype.Text `json:"contactDiscord"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) UpdateSubmissionDetails(ctx context.Context, arg UpdateSubmissionDetailsParams) (Submission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionDetails,
		arg.ID,
		arg.ArtistName,
		arg.PreferredDate,
		arg.Genre,
		arg.ExpectedDraw,
		arg.Links,
		arg.TechRider,
		arg.Message,
		arg.ContactDiscord,
		arg.Status,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.ArtistName,
		&i.PreferredDate,
		&i.Genre,
		&i.ExpectedDraw,
		&i.Links,
		&i.TechRider,
		&i.Message,
		&i.ContactDiscord,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}
