import { Button } from 'pyxis-components';
import { useGetArtistsQuery, useGetAttendanceQuery, useGetAuditLogQuery, useGetBookingsQuery, useGetCalendarQuery, useGetDiscordMappingsQuery, useGetSettingsQuery, useGetShowsQuery } from '../api/appApi';
import { artists as seedArtists, attendance as seedAttendance, auditLog as seedLog, bookings as seedBookings, calendarEvents as seedEvents, discordMappings as seedMappings, settings as seedSettings, shows as seedShows } from '../api/mockData';
import { AppShell } from '../components/shell/AppShell';
import { ArtistRoster, AttendancePanel, AuditLogPanel, BookingQueue, CalendarMonth, DashboardOverview, DiscordMappingPanel, NewShowModal, Panel, SettingsPanel, ShowsTable } from '../components/organisms/Panels';

export function DashboardPage() { const { data: shows = seedShows } = useGetShowsQuery(); const { data: bookings = seedBookings } = useGetBookingsQuery(); const { data: log = seedLog } = useGetAuditLogQuery(); return <AppShell page="dashboard" title="Welcome back, Ada" eyebrow="Home / Dashboard"><div data-section="dashboard-summary"><DashboardOverview shows={shows} bookings={bookings} log={log}/></div></AppShell>; }
export function ShowsPage() { const { data: shows = seedShows } = useGetShowsQuery(); return <AppShell page="shows" title="Shows" eyebrow="Home / Shows" action={<Button size="sm">New show</Button>}><Panel title="Confirmed · 6" section="shows-confirmed"><ShowsTable shows={shows.filter((s)=>s.status !== 'archived')}/></Panel><div style={{ height: 18 }}/><Panel title="Archived · 2" section="shows-archived"><ShowsTable shows={shows.filter((s)=>s.status === 'archived')}/></Panel></AppShell>; }
export function CalendarPage() { const { data: events = seedEvents } = useGetCalendarQuery(); return <AppShell page="calendar" title="Calendar" eyebrow="Home / Calendar"><Panel title="May at a glance" section="calendar-month"><CalendarMonth events={events}/></Panel></AppShell>; }
export function BookingsPage() { const { data: bookings = seedBookings } = useGetBookingsQuery(); return <AppShell page="bookings" title="Bookings" eyebrow="Home / Bookings"><Panel title="Awaiting review · 3" section="bookings-queue"><BookingQueue bookings={bookings}/></Panel></AppShell>; }
export function ArtistsPage() { const { data: artists = seedArtists } = useGetArtistsQuery(); return <AppShell page="artists" title="Artists" eyebrow="Home / Artists"><Panel title="All artists" section="artists-roster"><ArtistRoster artists={artists}/></Panel></AppShell>; }
export function AttendancePage() { const { data: entries = seedAttendance } = useGetAttendanceQuery(); return <AppShell page="attendance" title="Post-show log" eyebrow="Home / Post-show log"><Panel title="Past shows" section="attendance-past-shows"><AttendancePanel entries={entries}/></Panel></AppShell>; }
export function AuditLogPage() { const { data: log = seedLog } = useGetAuditLogQuery(); return <AppShell page="audit-log" title="Audit log" eyebrow="Home / Audit log"><Panel title="Activity" section="audit-log-activity"><AuditLogPanel log={log}/></Panel></AppShell>; }
export function DiscordPage() { const { data: mappings = seedMappings } = useGetDiscordMappingsQuery(); return <AppShell page="discord" title="Discord" eyebrow="Home / Discord"><Panel title="Channel mapping" section="discord-channel-mapping"><DiscordMappingPanel mappings={mappings}/></Panel></AppShell>; }
export function SettingsPage() { const { data: settings = seedSettings } = useGetSettingsQuery(); return <AppShell page="settings" title="Settings" eyebrow="Home / Settings"><Panel title="Space info" section="settings-space-info"><SettingsPanel settings={settings}/></Panel></AppShell>; }
export function LoginPage() { return <main className="app-login" data-page="login"><section><b>pyxis</b><h1>Welcome back</h1><p>Sign in to manage shows, bookings, artists, Discord, and post-show logs.</p><Button>Continue with Discord</Button></section></main>; }
export function SetupPage() { return <main className="app-login" data-page="setup"><section><b>pyxis</b><h1>Map your Discord channels</h1><p>Connect booking requests, upcoming shows, staff log, and post-show reporting.</p><Button>Finish setup</Button></section></main>; }
export function ModalShowcasePage() { return <><ShowsPage/><NewShowModal/></>; }
