import { useNavigate } from 'react-router-dom';
import { Button, Field, Input, PyxisMark } from 'pyxis-components';
import './Page.css';

export function SetupPage() {
  const navigate = useNavigate();
  const mappings = [['#upcoming-shows','847392017483620355','Public · bot posts + pins confirmed show announcements'],['#announcements','847392017483620356','Public · broader space announcements and cancellations'],['#staff','847392017483620357','Private · auto-archive notices, reminders, bot status'],['#booking-requests','847392017483620358','Private · incoming artist submissions land here']] as const;
  return <main className="app-setup-page" data-page="setup"><div className="app-setup-heading" data-section="setup-header"><div><PyxisMark size={28}/><b>pyxis</b></div><span className="app-eyebrow">Setup · 3 of 4</span><h1>Map your Discord channels</h1><p>Tell the bot where to post. Right-click any channel in Discord and choose <b>Copy Channel ID</b> (requires Developer Mode).</p></div><div className="app-setup-progress" data-section="setup-progress">{['Space','Server','Channels','Ready'].map((label,index)=><div key={label} data-active={index===2} data-done={index<2}><b>{index<2 ? '✓' : index+1}</b><span>{label}</span></div>)}</div><section className="app-setup-card" data-section="setup-channels">{mappings.map(([name,id,hint])=><Field key={name} label={name} hint={hint}><Input value={id} icon="compass" readOnly /></Field>)}<footer><Button variant="ghost" onClick={() => navigate('/settings')}>Back</Button><div><Button variant="outline" onClick={() => navigate('/')}>Skip for now</Button><Button iconRight="chevron-right" onClick={() => navigate('/discord')}>Continue</Button></div></footer></section><p className="app-setup-footnote">You can change any of this later under Settings → Discord.</p></main>;
}
