import type { Meta, StoryObj } from '@storybook/react';
import { auditLog, bookings, calendarEvents, settings, shows } from '../src/api/mockData';
import { ActivityFeedItem } from '../src/components/molecules/ActivityFeedItem';
import { BookingCard } from '../src/components/molecules/BookingCard';
import { CalendarEventChip } from '../src/components/molecules/CalendarEventChip';
import { DateChip } from '../src/components/atoms/DateChip';
import { DiscordChannelRow } from '../src/components/molecules/DiscordChannelRow';
import { MetricCard } from '../src/components/molecules/MetricCard';
import { SettingsToggleRow } from '../src/components/molecules/SettingsToggleRow';
import { StatusDot } from '../src/components/atoms/StatusDot';
import { TodayShowCard } from '../src/components/molecules/TodayShowCard';
import { DashboardOverview } from '../src/components/organisms/Panels';
const meta: Meta = { title: 'Pyxis App/Components' };
export default meta;
type Story = StoryObj;
export const MetricCardDefault: Story = { render: () => <div style={{ width: 231 }}><MetricCard label="Upcoming" value={6} caption="Next 60 days" tone="accent"/></div> };
export const StatusDots: Story = { render: () => <div style={{ display: 'flex', gap: 18, padding: 24 }}><StatusDot tone="confirmed"/><StatusDot tone="pending"/><StatusDot tone="declined"/><StatusDot tone="bot"/></div> };
export const DateChipDefault: Story = { render: () => <div style={{ padding: 24 }}><DateChip date="2025-05-02"/></div> };
export const ActivityItemDefault: Story = { render: () => <div style={{ width: 420, padding: 24 }}><ActivityFeedItem item={auditLog[0]}/></div> };
export const TodayShowDefault: Story = { render: () => <div style={{ width: 520, padding: 24 }}><TodayShowCard show={shows[0]}/></div> };
export const BookingCardDefault: Story = { render: () => <div style={{ width: 360, padding: 24 }}><BookingCard booking={bookings[0]}/></div> };
export const CalendarEventDefault: Story = { render: () => <div style={{ padding: 24 }}><CalendarEventChip event={calendarEvents[0]}/></div> };
export const DiscordRowDefault: Story = { render: () => <div style={{ width: 520, padding: 24 }}><DiscordChannelRow mapping={{ kind: 'bookingRequests', label: 'Booking requests', channelName: '#booking-requests', channelId: '847392017483620358', enabled: true }}/></div> };
export const SettingsToggleDefault: Story = { render: () => <div style={{ width: 520, padding: 24 }}><SettingsToggleRow label="Discord posting" description="Post approved events to mapped channels." enabled={settings.discordPosting}/></div> };
export const DashboardOverviewDefault: Story = { render: () => <div style={{ padding: 24 }}><DashboardOverview shows={shows} bookings={bookings} log={auditLog}/></div> };
