#!/usr/bin/env python3
"""Inventory Pyxis app prototype, package, playbook, and visual-diff inputs.

This is ticket-local research scaffolding, not a promoted project workflow.
It writes a concise Markdown inventory that can be cited from the design guide.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[6]
OUT = ROOT / "ttmp/2026/04/25/PYXIS-APP-REACT--build-pyxis-app-react-package-from-full-app-prototypes/various/01-source-inventory.md"

SECTIONS = {
    "Prototype standalone full app": "prototype-design/standalone/full-app",
    "Prototype standalone mobile": "prototype-design/standalone/mobile",
    "Prototype screen sources": "prototype-design/screens",
    "Prototype shared libs": "prototype-design/lib",
    "Current visual userland": "prototype-design/visual-diff/userland",
    "Current web packages": "web/packages",
    "Playbooks/docs": "docs",
}

SKIP_DIRS = {"node_modules", "dist", "storybook-static", ".git"}


def list_files(path: Path, max_depth: int = 3) -> list[str]:
    rows: list[str] = []
    if not path.exists():
        return ["(missing)"]
    base_depth = len(path.parts)
    for item in sorted(path.rglob("*")):
        if any(part in SKIP_DIRS for part in item.parts):
            continue
        if item.is_dir():
            continue
        if len(item.parts) - base_depth > max_depth:
            continue
        rows.append(str(item.relative_to(ROOT)))
    return rows


def main() -> None:
    lines = [
        "---",
        "Title: Pyxis app React source inventory",
        "Ticket: PYXIS-APP-REACT",
        "Status: active",
        "Topics:",
        "  - frontend",
        "  - visual-diff",
        "  - storybook",
        "  - pyxis",
        "  - rtk-query",
        "DocType: reference",
        "Intent: research",
        "Summary: Ticket-local inventory of prototype, package, playbook, and visual-diff sources for the pyxis-app React workflow guide.",
        "---",
        "",
        "# Pyxis App React Source Inventory",
        "",
        "Generated by `scripts/01-inventory-pyxis-app-sources.py`.",
        "",
    ]
    for title, rel in SECTIONS.items():
        lines += [f"## {title}", "", f"Path: `{rel}`", ""]
        for f in list_files(ROOT / rel):
            lines.append(f"- `{f}`")
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(OUT)


if __name__ == "__main__":
    main()
