export const endpoints = {
  session: '/api/app/session',
  shows: '/api/app/shows',
  show: (id: number) => `/api/app/shows/${id}`,
  showCancel: (id: number) => `/api/app/shows/${id}/cancel`,
  showArchive: (id: number) => `/api/app/shows/${id}/archive`,
  showAnnounce: (id: number) => `/api/app/shows/${id}/announce`,
  showFlyer: (id: number) => `/api/app/shows/${id}/flyer`,
  bookings: '/api/app/bookings',
  booking: (id: number) => `/api/app/bookings/${id}`,
  bookingApprove: (id: number) => `/api/app/bookings/${id}/approve`,
  bookingDecline: (id: number) => `/api/app/bookings/${id}/decline`,
  bookingReview: (id: number) => `/api/app/bookings/${id}/review`,
  artists: '/api/app/artists',
  artist: (id: number) => `/api/app/artists/${id}`,
  calendar: '/api/app/calendar',
  calendarHolds: '/api/app/calendar/holds',
  calendarHold: (id: number) => `/api/app/calendar/holds/${id}`,
  calendarBlocked: '/api/app/calendar/blocked',
  calendarBlockedDay: (id: number) => `/api/app/calendar/blocked/${id}`,
  attendance: '/api/app/attendance',
  attendanceShow: (showId: number) => `/api/app/attendance/${showId}`,
  auditLog: '/api/app/audit-log',
  discord: '/api/app/discord',
  settings: '/api/app/settings',
} as const;
